[tool.poetry]
name = "bmaptool"
version = "3.7.0"
license = "GPL-2.0-only"
description = "BMAP tools"
authors = ["Trevor Woerner <twoerner@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
six = "^1.16.0"
gpg = "^1.10.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
nose = "^1.3.7"

[tool.poetry.scripts]
bmaptool = "bmaptool.CLI:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
